import Foundation

enum Text {
    static let cm = "cm"
    static let inch = "in"
    static let ft = "ft"
    static let lb = "lb"
    static let kg = "kg"
    static let gender = "What's your gender?"
    static let height = "What's your height?"
    static let weight = "What's your weight?"
    static let notify = "Don't miss anything important"
    static let miss = "Don’t miss anything important"
    static let textLast = "Allow notification to get daily health insights control your stress level, and stay strong and vigorous"
    static let notifyText = "Allow notification to get daily health insights control your stress level, and stay strong and vigorous"
    static let next = "CONTINUE"
    static let allow = "ALLOW NOTIFICATION"
    static let male = "Male"
    static let female = "Female"
    static let non = "Non-bynary"
    static let pulse = "Your pulse"
    static let sleep = "Sleep time"
    static let steps = "Steps goal"
    static let pulseHeader =  "You may think all cholesterol is bad, but your body needs some to work right. Cholesterol is a waxy substance that your body makes and you also get from food. It allows your body to make vitamin D and certain hormones, including estrogen in women and testosterone in men, and helps with digestion"
    static let bpm = "bpm"
    static let measure = "measure"
    static let nice = "nice"
    static let check = "check your result"
    static let measuerInProgress = "measurement \n in progress"
    static let tapToMeasure = "Tap to start \n measure"
    static let stepsGo = "Steps"
    static let wait = "wait"
    static let noData = "\u{221E}"
}
